---
language: node_js
node_js:
  - 10.14.1

sudo: false

dist: trusty
addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-lts-3.4-without-fastboot
  - EMBER_TRY_SCENARIO=ember-lts-3.8-without-fastboot
  - EMBER_TRY_SCENARIO=ember-release-without-fastboot
  - EMBER_TRY_SCENARIO=ember-beta-without-fastboot
  - EMBER_TRY_SCENARIO=ember-canary-without-fastboot
  - EMBER_TRY_SCENARIO=ember-lts-3.4-with-fastboot
  - EMBER_TRY_SCENARIO=ember-lts-3.8-with-fastboot
  - EMBER_TRY_SCENARIO=ember-release-with-fastboot
  - EMBER_TRY_SCENARIO=ember-beta-with-fastboot
  - EMBER_TRY_SCENARIO=ember-canary-with-fastboot

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn run lint
  - yarn run lint-typescript
  - yarn run prettier-check
  # Usually, it’s ok to finish the test scenario without reverting
  # to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
