name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn run lint
      - name: Run Prettier
        run: yarn run prettier-check
      - name: Run type check
        run: yarn run type-check
      - name: Run Tests
        run: yarn run test:ember

  floating:
    name: Floating Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn run test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: test

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.12-without-fastboot
          - ember-lts-3.16-without-fastboot
          - ember-lts-3.20-without-fastboot
          - ember-lts-3.24-without-fastboot
          - ember-lts-3.28-without-fastboot
          - ember-release-without-fastboot
          - ember-lts-3.12-with-fastboot
          - ember-lts-3.16-with-fastboot
          - ember-lts-3.20-with-fastboot
          - ember-lts-3.24-with-fastboot
          - ember-lts-3.28-with-fastboot
          - ember-release-with-fastboot
          - embroider-safe
          - embroider-optimized
        allow-failure: [false]
        include:
          - try-scenario: ember-beta-without-fastboot
            allow-failure: true
          - try-scenario: ember-canary-without-fastboot
            allow-failure: true
          - try-scenario: ember-beta-with-fastboot
            allow-failure: true
          - try-scenario: ember-canary-with-fastboot
            allow-failure: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
